/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import produtos.FrmListaProd_1;
import produtos.FrmProdutos;
/**
 *
 * @author Ana Luisa
 */
public class MenuPrincipal extends javax.swing.JFrame {
   
    public static boolean fechado = false;
    public static boolean fechado1 = false;
    
    public boolean estaFechado(Object obj){
        JInternalFrame[] ativo = carregador.getAllFrames();
        boolean fechado = true;
        int i = 0;
        while(i < ativo.length && fechado){
            if(ativo[i] == obj){
                fechado = false;
                fechado1 = false;
                
            }
            
            i++;
        }
        
        return fechado;
    }
    
    
    //HORAS
    class horas implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            Date sistemaHora = new Date();
            String pmAm = "HH:mm:ss";
            SimpleDateFormat formato = new SimpleDateFormat(pmAm);
            Calendar now = Calendar.getInstance();
            hora.setText(String.format(formato.format(sistemaHora), now));
        }
    }

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        carregador = new principal.Carregador();
        painelCabecalho = new javax.swing.JPanel();
        hora = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        userConect = new javax.swing.JLabel();
        logouser = new javax.swing.JLabel();
        logodesconect = new javax.swing.JLabel();
        btnProduto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnProduto1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        painelPrincipal.setPreferredSize(new java.awt.Dimension(1280, 640));
        painelPrincipal.setLayout(new java.awt.BorderLayout());

        carregador.setMaximumSize(new java.awt.Dimension(1360, 760));
        carregador.setMinimumSize(new java.awt.Dimension(1360, 760));
        carregador.setName("carregador"); // NOI18N

        painelCabecalho.setBackground(new java.awt.Color(255, 222, 195));
        painelCabecalho.setPreferredSize(new java.awt.Dimension(1280, 125));
        painelCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hora.setForeground(new java.awt.Color(0, 0, 0));
        hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hora.setText("HORA");
        painelCabecalho.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 20, 225, -1));

        data.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        data.setForeground(new java.awt.Color(0, 0, 0));
        data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        data.setText("DIA - MES - ANO");
        painelCabecalho.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 225, -1));

        desc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        desc.setForeground(new java.awt.Color(0, 0, 0));
        desc.setText("DESCONECTAR");
        desc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descMouseClicked(evt);
            }
        });
        painelCabecalho.add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 110, -1));

        userConect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userConect.setForeground(new java.awt.Color(0, 0, 0));
        userConect.setText("USUARIO");
        painelCabecalho.add(userConect, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 101, -1));

        logouser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/conectado.png"))); // NOI18N
        painelCabecalho.add(logouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        logodesconect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logodesconect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/desconec.png"))); // NOI18N
        painelCabecalho.add(logodesconect, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        btnProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProduto.setForeground(new java.awt.Color(255, 255, 255));
        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/Produto.png"))); // NOI18N
        btnProduto.setText("PRODUTOS");
        btnProduto.setBorder(null);
        btnProduto.setContentAreaFilled(false);
        btnProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduto.setName("btnProduto"); // NOI18N
        btnProduto.setPreferredSize(new java.awt.Dimension(100, 120));
        btnProduto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/produtos2.png"))); // NOI18N
        btnProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });
        painelCabecalho.add(btnProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, 180, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/logo.png"))); // NOI18N
        painelCabecalho.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 190, 190));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Estoque de");
        painelCabecalho.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, -1, -1));

        btnProduto1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProduto1.setForeground(new java.awt.Color(255, 255, 255));
        btnProduto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/Produto.png"))); // NOI18N
        btnProduto1.setText("PRODUTOS");
        btnProduto1.setBorder(null);
        btnProduto1.setContentAreaFilled(false);
        btnProduto1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProduto1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduto1.setName("btnProduto"); // NOI18N
        btnProduto1.setPreferredSize(new java.awt.Dimension(100, 120));
        btnProduto1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/produtos2.png"))); // NOI18N
        btnProduto1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduto1ActionPerformed(evt);
            }
        });
        painelCabecalho.add(btnProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 180, 110));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Registrar novo ");
        painelCabecalho.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        carregador.add(painelCabecalho);
        painelCabecalho.setBounds(0, 0, 1810, 210);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/estoq.png"))); // NOI18N
        jLabel1.setText(" ");
        carregador.add(jLabel1);
        jLabel1.setBounds(-70, 210, 1350, 520);

        painelPrincipal.add(carregador, java.awt.BorderLayout.CENTER);

        getContentPane().add(painelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descMouseClicked
         
        //DESONECTAR USUARIO
        if (JOptionPane.showConfirmDialog(this, "Deseja fechar a sessão do usuário?", "Fechar Sessão", JOptionPane.YES_NO_OPTION, 0 
                )== JOptionPane.YES_OPTION) {
            this.dispose(); 
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);  
            
        }
    }//GEN-LAST:event_descMouseClicked

    produtos.FrmListaProd_1 tela;
    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
         
        //TELA DE ESTOQUE
        if(estaFechado(tela)){
            tela = new FrmListaProd_1();
            carregador.add(tela).setLocation(150,3);
            tela.show();
        }else{
            
             tela.toFront();
             tela.show();
        }
        
    }//GEN-LAST:event_btnProdutoActionPerformed

    produtos.FrmProdutos tela1;
    private void btnProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduto1ActionPerformed

        //TELA DE REGISTRO
        if(estaFechado(tela1)){
            tela1 = new FrmProdutos();
            carregador.add(tela1).setLocation(150,3);
            tela1.show();
        }else{
            tela1.toFront();
            tela1.show();
        }
    }//GEN-LAST:event_btnProduto1ActionPerformed

    
   
     private void logodesconectMouseClicked(java.awt.event.MouseEvent evt) {                                           
        if (JOptionPane.showConfirmDialog(this, "Deseja fechar a sessão do usuário?", "Fechar Sessão", JOptionPane.YES_NO_OPTION, 0
                ) == JOptionPane.YES_OPTION) {
            this.dispose(); 
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);  
            
         }
    }
     
     //DATA
      private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        Date sistemaData = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd MMMM yyyy");
        data.setText(formato.format(sistemaData));
        
        //HORA DO SISTEMA
        Timer hr = new Timer(100, new MenuPrincipal.horas());
        hr.start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipal tela = new MenuPrincipal();
                tela.setLocationRelativeTo(null);
                tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnProduto1;
    public static principal.Carregador carregador;
    private javax.swing.JLabel data;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logodesconect;
    private javax.swing.JLabel logouser;
    private javax.swing.JPanel painelCabecalho;
    private javax.swing.JPanel painelPrincipal;
    public static javax.swing.JLabel userConect;
    // End of variables declaration//GEN-END:variables
}
